// Generated by gencpp from file package/gnss.msg
// DO NOT EDIT!


#ifndef PACKAGE_MESSAGE_GNSS_H
#define PACKAGE_MESSAGE_GNSS_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace package
{
template <class ContainerAllocator>
struct gnss_
{
  typedef gnss_<ContainerAllocator> Type;

  gnss_()
    : East(0.0)
    , North(0.0)
    , Yaw(0.0)  {
    }
  gnss_(const ContainerAllocator& _alloc)
    : East(0.0)
    , North(0.0)
    , Yaw(0.0)  {
  (void)_alloc;
    }



   typedef double _East_type;
  _East_type East;

   typedef double _North_type;
  _North_type North;

   typedef double _Yaw_type;
  _Yaw_type Yaw;





  typedef boost::shared_ptr< ::package::gnss_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::package::gnss_<ContainerAllocator> const> ConstPtr;

}; // struct gnss_

typedef ::package::gnss_<std::allocator<void> > gnss;

typedef boost::shared_ptr< ::package::gnss > gnssPtr;
typedef boost::shared_ptr< ::package::gnss const> gnssConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::package::gnss_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::package::gnss_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::package::gnss_<ContainerAllocator1> & lhs, const ::package::gnss_<ContainerAllocator2> & rhs)
{
  return lhs.East == rhs.East &&
    lhs.North == rhs.North &&
    lhs.Yaw == rhs.Yaw;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::package::gnss_<ContainerAllocator1> & lhs, const ::package::gnss_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace package

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::package::gnss_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::package::gnss_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::package::gnss_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::package::gnss_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::package::gnss_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::package::gnss_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::package::gnss_<ContainerAllocator> >
{
  static const char* value()
  {
    return "786bb79528800c839905020a7bf7d1ae";
  }

  static const char* value(const ::package::gnss_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x786bb79528800c83ULL;
  static const uint64_t static_value2 = 0x9905020a7bf7d1aeULL;
};

template<class ContainerAllocator>
struct DataType< ::package::gnss_<ContainerAllocator> >
{
  static const char* value()
  {
    return "package/gnss";
  }

  static const char* value(const ::package::gnss_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::package::gnss_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 East\n"
"float64 North\n"
"float64 Yaw\n"
;
  }

  static const char* value(const ::package::gnss_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::package::gnss_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.East);
      stream.next(m.North);
      stream.next(m.Yaw);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct gnss_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::package::gnss_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::package::gnss_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "East: ";
    Printer<double>::stream(s, indent + "  ", v.East);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "North: ";
    Printer<double>::stream(s, indent + "  ", v.North);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "Yaw: ";
    Printer<double>::stream(s, indent + "  ", v.Yaw);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PACKAGE_MESSAGE_GNSS_H
