// Generated by gencpp from file package/object.msg
// DO NOT EDIT!


#ifndef PACKAGE_MESSAGE_OBJECT_H
#define PACKAGE_MESSAGE_OBJECT_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace package
{
template <class ContainerAllocator>
struct object_
{
  typedef object_<ContainerAllocator> Type;

  object_()
    : East(0.0)
    , North(0.0)
    , Yaw(0.0)
    , Vel(0.0)  {
    }
  object_(const ContainerAllocator& _alloc)
    : East(0.0)
    , North(0.0)
    , Yaw(0.0)
    , Vel(0.0)  {
  (void)_alloc;
    }



   typedef double _East_type;
  _East_type East;

   typedef double _North_type;
  _North_type North;

   typedef double _Yaw_type;
  _Yaw_type Yaw;

   typedef double _Vel_type;
  _Vel_type Vel;





  typedef boost::shared_ptr< ::package::object_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::package::object_<ContainerAllocator> const> ConstPtr;

}; // struct object_

typedef ::package::object_<std::allocator<void> > object;

typedef boost::shared_ptr< ::package::object > objectPtr;
typedef boost::shared_ptr< ::package::object const> objectConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::package::object_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::package::object_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::package::object_<ContainerAllocator1> & lhs, const ::package::object_<ContainerAllocator2> & rhs)
{
  return lhs.East == rhs.East &&
    lhs.North == rhs.North &&
    lhs.Yaw == rhs.Yaw &&
    lhs.Vel == rhs.Vel;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::package::object_<ContainerAllocator1> & lhs, const ::package::object_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace package

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::package::object_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::package::object_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::package::object_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::package::object_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::package::object_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::package::object_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::package::object_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1738d351724b3c4d39cc9127cdfa9d03";
  }

  static const char* value(const ::package::object_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1738d351724b3c4dULL;
  static const uint64_t static_value2 = 0x39cc9127cdfa9d03ULL;
};

template<class ContainerAllocator>
struct DataType< ::package::object_<ContainerAllocator> >
{
  static const char* value()
  {
    return "package/object";
  }

  static const char* value(const ::package::object_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::package::object_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 East\n"
"float64 North\n"
"float64 Yaw\n"
"float64 Vel\n"
;
  }

  static const char* value(const ::package::object_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::package::object_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.East);
      stream.next(m.North);
      stream.next(m.Yaw);
      stream.next(m.Vel);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct object_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::package::object_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::package::object_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "East: ";
    Printer<double>::stream(s, indent + "  ", v.East);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "North: ";
    Printer<double>::stream(s, indent + "  ", v.North);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "Yaw: ";
    Printer<double>::stream(s, indent + "  ", v.Yaw);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "Vel: ";
    Printer<double>::stream(s, indent + "  ", v.Vel);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PACKAGE_MESSAGE_OBJECT_H
